# Site settings
title: TKVTV with VANILLA
description: バニラバニラ求人サイト
baseurl: "/page80" # the subpath of your site, e.g. /blog
url: "https://takagotch.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Takashi Yoshioka
user_description: Crypto Developer
user_title: Crypto Developer
email: anon@anon.com
twitter_username: takagotch
github_username:  takagotch
gplus_username:   takagotch
disqus_username:  takagotch

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
